application:
  diffColorRGB: 0x99ff0000
  schema: http
  host: localhost
  port: 8008
  context:
  files:
    resultPrefix: viff
    localPath: viff-storage

eureka:
  instance:
    hostname: localhost
    nonSecurePort: 8761
