server:
  port: 8008

spring:
  application:
    name: viff-storage
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/viff_storage?useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:

application:
  schema: http
  host: localhost
  port: 8008
  context:
  files:
    localPath: viff-storage
    maxSize: 5MB
    root: ${application.schema}/${application.host}/${application.port}


flyway:
  url: ${spring.datasource.url}
  user: ${spring.datasource.username}
  password: ${spring.datasource.password}

eureka:
  instance:
    hostname: localhost
    nonSecurePort: 8761